config/routes.rb
Rails.application.routes.draw do
  get "documentaryfilm/index"
  get "documentaryfilm/new"
  get "documentaryfilm/create"
  
  get "serie/index"
  get "serie/new"
  get "serie/create"

  get "movie/index"
  get "movie/new"
  get "movie/create"


  post "movie", to: "movie#create" 
  post "serie", to: "serie#create" 
  post "documentaryfilm", to: "documentaryfilm#create" 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root "movie#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/series.rb
class Series < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/documentaryfilm_controller.rb
class DocumentaryfilmController < ApplicationController
  def index
    @documentaryfilm = documentaryfilm.all
  end

  def new
      #Captura los datos enviados en el formulario
      @documentaryfilm = Post.new
  end

  def create
      @documentaryfilm = Post.new(documentaryfilm_params)
      pp @documentaryfilm

        if @documentaryfilm.save 
            redirect_to root_path  
            # redirect_to posts_index_path
        else
          render  :new
        end 
  end


  private

  def documentaryfilm_params
      params.require(:documentaryfilm).permit(:name, :synopsis. :director)
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
    def index
        # @movie = Post.all
        @movie = Post.all
    end

    def new
         @movie = Post.new
    end

    def create
      @movie = Post.new(movie_params)
      pp @movie
        if  @movie.save 
              redirect_to root_path  
              # redirect_to posts_index_path
          else
            render  :new
        end 
    end


  private

  def movie_params
      params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/serie_controller.rb
class SerieController < ApplicationController
  def index
    @serie = serie.all
end

def new
    #Captura los datos enviados en el formulario
    @serie = Post.new
end

def create
  @serie = Post.new(serie_params)
  pp @serie
  if  @serie.save 
        redirect_to root_path  
        # redirect_to posts_index_path
    else
      render  :new
    end 
end


private

def serie_params
    params.require(:serie).permit(:name, :synopsis. :director)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentaryfilm_helper.rb
module DocumentaryfilmHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/serie_helper.rb
module SerieHelper
end

app/views/documentaryfilm/create.html.erb
<h1>Documentaryfilm#create</h1>
<p>Find me in app/views/documentaryfilm/create.html.erb</p>

app/views/documentaryfilm/index.html.erb
<h1>Documentaryfilm#index</h1>
<p>Find me in app/views/documentaryfilm/index.html.erb</p>

app/views/documentaryfilm/new.html.erb
<h1>Documentaryfilm#new</h1>
<p>Find me in app/views/documentaryfilm/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Desafio M5 D9 Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">

 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
   rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>


    <%# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"> %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>


  </body>
</html>

app/views/movie/create.html.erb
<h1>Movie#create</h1>
<p>Find me in app/views/movie/create.html.erb</p>

app/views/movie/index.html.erb
<h1 class = "container pb-2">Mostrando todos las Movies ingresados =</h1>

 
 <div class = "container  ">

        <h2 class= "bg-success-subtle border border-success-subtle rounded-4">Titulo:  </h2>
        <p>Contenido:  </p>

</div>

 
 <div class = "container">
    <%= link_to "Agregar nuevo Movies", movie_new_path,  class: "btn btn-success"%>
 </div>

app/views/movie/new.html.erb
<h1 class = "container py-5 text-center">Crear Movies  </h1>


<%= form_with model: @movie, method: :post do |form| %>
    <div class="col-4  container ">
            <div class="py-3">
                <%= form.label :name, "Nombre de la pelicula", class: "form-label " %>
                <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="py-3">
                <%= form.label :synopsis, "synopsis de la pelicula", class: "form-label " %>
                <%= form.text_field :synopsis, class: "form-control" %>
            </div>
            <div class="py-3">
                <%= form.label :director, "director de la pelicula", class: "form-label" %>
                <%= form.text_field :director, class: "form-control" %>
            </div>
            <div class="text-center py-5">
                <%= form.submit "Submit", class: "btn btn-primary" %>
            </div>
    </div>
 <% end %>

app/views/serie/create.html.erb
<h1>Serie#create</h1>
<p>Find me in app/views/serie/create.html.erb</p>

app/views/serie/index.html.erb
<h1>Serie#index</h1>
<p>Find me in app/views/serie/index.html.erb</p>

app/views/serie/new.html.erb
<h1>Serie#new</h1>
<p>Find me in app/views/serie/new.html.erb</p>